server:
  port: 21005
spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.9.22:3306/microwave?serverTimezone=UTC&characterEncoding=utf-8
    username: yimai
    password: domore
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  devtools:
    restart:
      enabled: true

  # 修改静态资源前缀
  mvc:
    static-path-pattern: /my/**

mybatis:
  type-aliases-package: com.sylar.model
  mapper-locations: classpath:mapper/**/*.xml
